### PR TITLE
Fix configure and Makefile for MinGW

### PR DESCRIPTION
**Pull request by pali**
Current Makefile does not work with MinGW cross compilers. Fix it together with configure script for cross compilation.

### CODE REVIEW

**Review by gollux — CHANGES_REQUESTED** [review]
Generally, it looks OK. The `$(EXEEXT)` part is ugly as hell, but probably unavoidable.

The command used to compile pciutils on Windows should better be written in `README.Windows` instead of hiding it inside commit messages :)

**Comment by pali** [comment]
Done! I rebased code on top of the master branch and added new commit with compile instruction.

**Comment by gollux** [comment]
Could you please rebase it again against the current master?

**Comment by pali** [comment]
Done again!

**Pull request merged**
