### PR TITLE
Minor fix-ups for macOS

### PR DESCRIPTION
**Pull request by barracuda156**
See: https://github.com/pciutils/pciutils/issues/145

### CODE REVIEW

**Comment by gollux** [comment]
`<stdlib.h>` itself should be sufficient, I added it and removed `<malloc.h>` altogether.

Could you please test the current master?

**Comment by barracuda156** [comment]
@gollux Sure, let me try.

**Comment by barracuda156** [comment]
Maybe just misdetected build arch now matters while was not affecting the build previously. I will try forcing the correct choice.

**Comment by barracuda156** [comment]
Closing, since it has been fixed in the master now.

**Pull request closed without merging**
