### PR TITLE
Makefile: don't hardcode gcc

### PR DESCRIPTION
**Pull request by vcunat**
I believe "cc" is a much better default nowadays.
Another approach would be to (also) use "?=" for these variables.

### CODE REVIEW

**Comment by vcunat** [comment]
With this, clang build seems to just work for me on Linux and apparently [also on macOS](https://github.com/NixOS/nixpkgs/pull/98609).

**Comment by gollux** [comment]
However, I think we still require real GCC. Or are there any other compilers which support passing version scripts to the linker?

**Comment by gollux** [comment]
I gently remind you that this is not resolved yet.

**Comment by vcunat** [comment]
:-)  ah, right.  I still had it on my todo list, but it's a bit like stack with more incoming stuff than outgoing.

So I now tried two builds, gcc 10 and clang 13, and compared `nm -D libpci.so`.  Symbol versions are the same there.  (Though I'm certainly no expert on symbol versioning, so I may be doing it wrong.)

<details><pre>
(clang)
                 U access@GLIBC_2.2.5
                 U basename@GLIBC_2.2.5
                 U close@GLIBC_2.2.5
                 U closedir@GLIBC_2.2.5
                 U __ctype_b_loc@GLIBC_2.3
                 w __cxa_finalize@GLIBC_2.2.5
                 U __errno_location@GLIBC_2.2.5
                 U exit@GLIBC_2.2.5
                 U fclose@GLIBC_2.2.5
                 U feof@GLIBC_2.2.5
                 U ferror@GLIBC_2.2.5
                 U fflush@GLIBC_2.2.5
                 U fgets@GLIBC_2.2.5
                 U fopen@GLIBC_2.2.5
                 U __fprintf_chk@GLIBC_2.3.4
                 U fputc@GLIBC_2.2.5
                 U free@GLIBC_2.2.5
                 U fwrite@GLIBC_2.2.5
                 U gethostname@GLIBC_2.2.5
                 U getpid@GLIBC_2.2.5
                 U getpwuid@GLIBC_2.2.5
                 U getuid@GLIBC_2.2.5
                 w __gmon_start__
                 U __h_errno_location@GLIBC_2.2.5
                 U iopl@GLIBC_2.2.5
                 U __isoc99_sscanf@GLIBC_2.7
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
0000000000000000 A LIBPCI_3.0
0000000000000000 A LIBPCI_3.1
0000000000000000 A LIBPCI_3.2
0000000000000000 A LIBPCI_3.3
0000000000000000 A LIBPCI_3.4
0000000000000000 A LIBPCI_3.5
0000000000000000 A LIBPCI_3.6
0000000000000000 A LIBPCI_3.7
                 U malloc@GLIBC_2.2.5
                 U memcpy@GLIBC_2.14
                 U __memcpy_chk@GLIBC_2.3.4
                 U memset@GLIBC_2.2.5
                 U open@GLIBC_2.2.5
                 U opendir@GLIBC_2.2.5
0000000000003640 T pci_alloc@@LIBPCI_3.0
0000000000003b60 T pci_cleanup@@LIBPCI_3.0
0000000000004150 T pci_fill_info@LIBPCI_3.0
0000000000004150 T pci_fill_info@LIBPCI_3.2
0000000000004150 T pci_fill_info@LIBPCI_3.4
0000000000004150 T pci_fill_info@@LIBPCI_3.5
0000000000004150 T pci_fill_info@LIBPCI_3.1
0000000000004150 T pci_fill_info@LIBPCI_3.3
00000000000063c0 T pci_filter_init@LIBPCI_3.0
0000000000005e30 T pci_filter_init@@LIBPCI_3.3
00000000000062f0 T pci_filter_match@@LIBPCI_3.3
00000000000064e0 T pci_filter_match@LIBPCI_3.0
00000000000060f0 T pci_filter_parse_id@@LIBPCI_3.3
0000000000006450 T pci_filter_parse_id@LIBPCI_3.0
00000000000063e0 T pci_filter_parse_slot@LIBPCI_3.0
0000000000005e40 T pci_filter_parse_slot@@LIBPCI_3.3
0000000000008450 T pci_find_cap@@LIBPCI_3.1
00000000000084b0 T pci_find_cap_nr@@LIBPCI_3.7
0000000000003d00 T pci_free_dev@@LIBPCI_3.0
0000000000007360 T pci_free_name_list@@LIBPCI_3.0
0000000000003c70 T pci_get_dev@@LIBPCI_3.0
0000000000003610 T pci_get_method_name@@LIBPCI_3.0
0000000000007f10 T pci_get_param@@LIBPCI_3.0
0000000000004290 T pci_get_string_property@@LIBPCI_3.6
0000000000007c30 T pci_id_cache_flush@@LIBPCI_3.0
0000000000003730 T pci_init@LIBPCI_3.0
0000000000003730 T pci_init@@LIBPCI_3.5
0000000000006840 T pci_load_name_list@@LIBPCI_3.0
00000000000035b0 T pci_lookup_method@@LIBPCI_3.0
0000000000004fd0 T pci_lookup_name@@LIBPCI_3.0
0000000000003f10 T pci_read_block@@LIBPCI_3.0
0000000000003d60 T pci_read_byte@@LIBPCI_3.0
0000000000003e70 T pci_read_long@@LIBPCI_3.0
0000000000003f20 T pci_read_vpd@@LIBPCI_3.1
0000000000003dd0 T pci_read_word@@LIBPCI_3.0
0000000000003bc0 T pci_scan_bus@@LIBPCI_3.0
0000000000007390 T pci_set_name_list_path@@LIBPCI_3.0
0000000000008040 T pci_set_param@@LIBPCI_3.0
00000000000041e0 T pci_setup_cache@@LIBPCI_3.0
0000000000008110 T pci_walk_params@@LIBPCI_3.0
00000000000040e0 T pci_write_block@@LIBPCI_3.0
0000000000003f40 T pci_write_byte@@LIBPCI_3.0
0000000000004040 T pci_write_long@@LIBPCI_3.0
0000000000003fa0 T pci_write_word@@LIBPCI_3.0
                 U pread@GLIBC_2.2.5
                 U pwrite@GLIBC_2.2.5
                 U read@GLIBC_2.2.5
                 U readdir@GLIBC_2.2.5
                 U readlink@GLIBC_2.2.5
                 U realpath@GLIBC_2.3
                 U rename@GLIBC_2.2.5
                 U __res_init@GLIBC_2.2.5
                 U __res_query@GLIBC_2.2.5
                 U __snprintf_chk@GLIBC_2.3.4
                 U __sprintf_chk@GLIBC_2.3.4
                 U __stack_chk_fail@GLIBC_2.4
                 U stderr@GLIBC_2.2.5
                 U stdout@GLIBC_2.2.5
                 U __strcat_chk@GLIBC_2.3.4
                 U strchr@GLIBC_2.2.5
                 U strcmp@GLIBC_2.2.5
                 U strcpy@GLIBC_2.2.5
                 U strdup@GLIBC_2.2.5
                 U strerror@GLIBC_2.2.5
                 U strlen@GLIBC_2.2.5
                 U strncmp@GLIBC_2.2.5
                 U strrchr@GLIBC_2.2.5
                 U strtol@GLIBC_2.2.5
                 U unlink@GLIBC_2.2.5
                 U __vfprintf_chk@GLIBC_2.3.4
</pre></details>

**Comment by pali** [comment]
This change breaks cross-compilation as with `CROSS_COMPILE=arm-linux-gnueabi-` now make throws an error:
```
make[1]: arm-linux-gnueabi-cc: Command not found
```

**Comment by gollux** [comment]
That's bad... Let's try using "cc" when building natively and "gcc" when cross-compiling.

**Comment by pali** [comment]
Adding another option `CC=arm-linux-gnueabi-gcc` makes it working again... But that would mean to update all build scripts which calls make to add additional `CC=` options.

**Comment by vcunat** [comment]
Oh, I'm sorry.  I don't really know which way will break the least fraction of systems.

I'm not very good with cross; on a quick search, cross-prefix + cc is even [the recommended way](https://nixos.org/manual/nixpkgs/stable/#ssec-cross-cookbook) in "our system", though I remember they've put lots of effort into making cross behave better across various combinations.

**Pull request merged**
