### PR TITLE
Add SylixOS Porting.

### PR DESCRIPTION
**Pull request by gongyujian**

### CODE REVIEW

**Comment by gollux** [comment]
Hello!

Sorry for the delayed review. Generally, I will be glad to accept your SylixOS port. However, you should clean it up first:

- You should keep modifications to generic parts of the library to the bare minimum. Why do you ifdef out xmalloc()? Why do you make a separate copy of parse_generic_option()?
- All documentation and comments must be in English.
- You should make unrelated changes to maintainer scripts
- If you want to modify pci.ids, please submit updates via the web interface at https://pci-ids.ucw.cz/

Thanks!

**Comment by gongyujian** [comment]
Hello!

Thank you for your reply.

You should keep modifications to generic parts of the library to the bare minimum. Why do you ifdef out xmalloc()? Why do you make a separate copy of parse_generic_option()?
    

- The SylixOS function  prototype is as follows and transplants with standard c library.
      void *xmalloc(size_t stSize)  void *xrealloc(void *pvPtr, size_t stNewSize) char *xstrdup(const char *pcStr)
  

-  'optarg' of the  SylixOS is a macro definition rather than a variable. (#define optarg (*API_TShellOptArg())).

All documentation and comments must be in English.
    

- I have modified all documents and comments into English .

You should make unrelated changes to maintainer scripts
    

- I have resubmitted and all scripts are consistent.

If you want to modify pci.ids, please submit updates via the web interface at https://pci-ids.ucw.cz/
   

-  I think i need'nt modify pci.ids ，just using this is OK!

Thanks!

**Comment by gongyujian** [comment]
Hello!
Thank you for your reply.
    You should keep modifications to generic parts of the library to the bare minimum. Why do you ifdef out xmalloc()? Why do you make a separate copy of parse_generic_option()?
The SylixOS function prototype is as follows and transplants with standard c library.
void *xmalloc(size_t stSize) void *xrealloc(void *pvPtr, size_t stNewSize) char *xstrdup(const char *pcStr)
'optarg' of the SylixOS is a macro definition rather than a variable. (#define optarg (*API_TShellOptArg())).
    All documentation and comments must be in English.
I have modified all documents and comments into English .
    You should make unrelated changes to maintainer scripts
I have resubmitted and all scripts are consistent.
    If you want to modify pci.ids, please submit updates via the web interface at https://pci-ids.ucw.cz/
I think i need'nt modify pci.ids ，just using this is OK!
Thanks!




发件人：Martin Mareš <notifications@github.com>
发送时间：2018-03-17 00:42
主题：Re: [pciutils/pciutils] Add SylixOS Porting. (#3)
收件人："pciutils/pciutils"<pciutils@noreply.github.com>
抄送："YuJian.Gong"<gongyujian_king@163.com>,"Author"<author@noreply.github.com>

Hello!
Sorry for the delayed review. Generally, I will be glad to accept your SylixOS port. However, you should clean it up first:
You should keep modifications to generic parts of the library to the bare minimum. Why do you ifdef out xmalloc()? Why do you make a separate copy of parse_generic_option()? 
All documentation and comments must be in English. 
You should make unrelated changes to maintainer scripts 
If you want to modify pci.ids, please submit updates via the web interface at https://pci-ids.ucw.cz/ 
Thanks!

**Comment by gollux** [comment]
I began merging your changes to a "sylixos" branch in my repository.

I started with changes to generic code: prototypes of xmalloc() etc.,
avoiding optarg.

You are adding an option 'S' to parse_generic_option(), but that is
not going to work, because you are not including it in the GENERIC_OPTIONS
macro. What is the reason for adding an option like that? Is "-A SylixOS-PCI"
not enough? (BTW, it might be better to rename the back-end to something
easier to type.)

By the way, wouldn't it be better to prefer the SylixOS access method
over Intel conf1/conf2 when both are available? Changing the probe order
is unfortunately not trivial, because it defined by the order of access
methods in the pci_methods array, which we cannot change any longer as it
is a part of the ABI (via the PCI_ACCESS_xxx constants). However, I can
define a separate probing order if you want.

Now, to the back-end source file itself:

- sylixos-ports.c is not a good name, because the back-end does not access
  I/O ports at all :)  Better rename it to sylixos-device.c, or maybe just
  sylixos.c.

- I would appreciate if you followed the coding style of the rest of the
  pciutils: indentation, use of parentheses and so on.

- PCI_VENDOR_ID_IS_INVALIDATE should be PCI_VENDOR_ID_IS_INVALID, shouldn't it?

- Why do you introduce a separate probing mechanism, which looks very similar
  to pci_generic_scan_bus()? What are the important differences?

- What is the logic behind a->fd? As far as I understand the code, it is never
  set to anything else than -1 and thus closing it in sylixos_cleanup() is
  pointless.

- sylixos_fill_info() should not read the resources unless it is given flags
  related to resources. Also, it should not modify d->known_fields, but include
  the newly acquired flags in its return value.

- In the same function, you are doing "hResource = &hDevHandle->PCIDEV_tResource[i];"
  and then testing hResource for NULL. It does not look right: either PCIDEV_tResource
  is an array inside the device handle structure (and then a pointer to it can be
  never NULL), or it is a pointer to an array (and then it should be tested once
  before the whole loop).

Could you please fix it?

**Comment by gongyujian** [comment]
- I do not need PCI_HAVE_PM_DUMP, need you to modify the configure file.

Why do you introduce a separate probing mechanism, which looks very similar
  to pci_generic_scan_bus()? What are the important differences?

- On some platforms require environment variables.

Could you please fix it?
- I have fixed.

**Comment by gollux** [comment]
> - I do not need PCI_HAVE_PM_DUMP, need you to modify the configure file.

Why do you want to leave out PCI_HAVE_PM_DUMP? It is independent
of the OS and it should be always available.

> Why do you introduce a separate probing mechanism, which looks very similar
>   to pci_generic_scan_bus()? What are the important differences?
> 
> - On some platforms require environment variables.

I do not understand this. Could you please elaborate?

**Comment by gongyujian** [comment]
- I got it wrong, you are right.

- PCI_HAVE_PM_DUMP is independent of the OS and it should be always available.

By the way, wouldn't it be better to prefer the SylixOS access method
over Intel conf1/conf2 when both are available? Changing the probe order
is unfortunately not trivial, because it defined by the order of access
methods in the pci_methods array, which we cannot change any longer as it
is a part of the ABI (via the PCI_ACCESS_xxx constants). However, I can
define a separate probing order if you want.

- I need a probing sequence to access SylixOS method.

**Comment by gollux** [comment]
> - I need a probing sequence to access SylixOS method.

OK, I just added it to my sylixos branch.

**Comment by gongyujian** [comment]
I would appreciate if you merge into the master.
I will be more convenient for synchronization.

**Comment by gollux** [comment]
> I would appreciate if you merge into the master.
> I will be more convenient for synchronization.

Sorry, I would like to keep it in a separate branch before
it is completed, so that master is always in clean and working
state.

However, you can simply rebase your branch on the top of my
sylixos branch.

**Comment by gongyujian** [comment]
OK, Thank you for your merger.

**Comment by gollux** [comment]
> OK, Thank you for your merger.

So far, only the generic parts are merged.

I am still waiting for reasons why do you implement a separate
probe routine, quite similar to the generic probe.

**Comment by gongyujian** [comment]
My previous version used pci_generic_scan.

I found this method wrong on the PowerPC P4080 platform.

I Cannot use PCI_HEADER_TYPE_BRIDGE or PCI_HEADER_TYPE_CARDBUS to determine whether to perform cyclic scan, Need to actively scan through all devices.

I will use system environment variables to determine whether to perform all device traversal scans.

**Comment by gongyujian** [comment]
- SylixOS built-in command pcis:
[root@sylixos:/root]# pcis
PCI info:
Bus  0 Slot  0 Function 0 VendorID 1957 DevieceID 400:
  Class 11 [Processor] Sub 32 [Power PC] Prog-if 0 []
    IRQ Line-0 Pin-0
    Latency=0 SecLatency=0 PriBus=0 SecBus=1 SubBus=1
    I/O behind 00001111 Memory behind 80008000
    I/O 11-22 Mem 8000-10000 Rom 0
Bus  1 Slot  0 Function 0 VendorID 1b21 DevieceID 612:
  Class 1 [Mass storage controller] Sub 6 [SATA controller] Prog-if 1 [AHCI 1.0]
    IRQ Line-0 Pin-1
    Latency=0 Min Gnt=0 Max lat=0
    Base0 00001001 Base1 00001009 Base2 00001011
    Base3 00001019 Base4 00001021 Base5 80000000
    Rom 80010000 SubVendorID 1b21 SubSystemID 1060
    Region 0: I/O ports at 1000 [Size 8] [flags 00040101] 
    Region 1: I/O ports at 1008 [Size 4] [flags 00040101] 
    Region 2: I/O ports at 1010 [Size 8] [flags 00040101] 
    Region 3: I/O ports at 1018 [Size 4] [flags 00040101] 
    Region 4: I/O ports at 1020 [Size 32] [flags 00040101] 
    Region 5: Memory at 80000000 [Size 512] [flags 00040200]  (32-bit non-pre)
    Region 6: Expansion ROM at 80010000 [Size 64K] [flags 00046200]  (32-bit pre)
    Irq start 22 end 22 [flags 00000400] 
Bus  2 Slot  0 Function 0 VendorID 1957 DevieceID 400:
  Class 11 [Processor] Sub 32 [Power PC] Prog-if 0 []
    IRQ Line-0 Pin-0
    Latency=0 SecLatency=0 PriBus=0 SecBus=1 SubBus=1
    I/O behind 20001111 Memory behind c1f0c000
    I/O 11-22 Mem c000-181f0 Rom 0
Bus  3 Slot  0 Function 0 VendorID 8086 DevieceID 10c9:
  Class 2 [Network controller] Sub 0 [Ethernet controller] Prog-if 0 []
    IRQ Line-0 Pin-1
    Latency=0 Min Gnt=0 Max lat=0
    Base0 c0000000 Base1 c0400000 Base2 00001001
    Base3 c0800000 Base4 00000000 Base5 00000000
    Rom c0c00000 SubVendorID 8086 SubSystemID a03c
    Region 0: Memory at c0000000 [Size 128K] [flags 00040200]  (32-bit non-pre)
    Region 1: Memory at c0400000 [Size 4M] [flags 00040200]  (32-bit non-pre)
    Region 2: I/O ports at 1000 [Size 32] [flags 00040101] 
    Region 3: Memory at c0800000 [Size 16K] [flags 00040200]  (32-bit non-pre)
    Region 6: Expansion ROM at c0c00000 [Size 4M] [flags 00046200]  (32-bit pre)
    Irq start 23 end 23 [flags 00000400] 
Bus  3 Slot  0 Function 1 VendorID 8086 DevieceID 10c9:
  Class 2 [Network controller] Sub 0 [Ethernet controller] Prog-if 0 []
    IRQ Line-0 Pin-2
    Latency=0 Min Gnt=0 Max lat=0
    Base0 c1000000 Base1 c1400000 Base2 00001021
    Base3 c1800000 Base4 00000000 Base5 00000000
    Rom c1c00000 SubVendorID 8086 SubSystemID a03c
    Region 0: Memory at c1000000 [Size 128K] [flags 00040200]  (32-bit non-pre)
    Region 1: Memory at c[root@sylixos:/root]# 

- lspci :
[root@sylixos:/root]# lspci
00:00.0 Power PC: Freescale Semiconductor Inc P4080E (rev 30)
01:00.0 SATA controller: ASMedia Technology Inc. ASM1062 Serial ATA Controller (rev 01)

**Comment by gollux** [comment]
I merged your driver and tried to simplify its probe logic.

Could you please try in on your machines, including the problematic PowerPC
platform?

**Comment by gongyujian** [comment]
My new submission has been tested on the x86 and PowerPC P4080 platform.

**Comment by gollux** [comment]
> My new submission has been tested on the x86 and PowerPC P4080 platform.

Sorry if I wasn't clear. I wanted you to test the code in *my*
sylixos branch.

**Comment by gongyujian** [comment]
I need to add SylixOS device methods in pci_methods, etc. The rest is exactly the same as your sylixos branch, so I tested it on my own branch.
Please help me check if my processing is correct. 
Thank you.

**Comment by gongyujian** [comment]
Sorry, I need to check again.

**Comment by gongyujian** [comment]
Sorry, I can't find the sylixos-device.c file in your sylixos branch. 

The commit I can see is ‘Introduced an explicit probe sequence’.

Did you not submit it?

**Comment by gollux** [comment]
> Sorry, I can't find the sylixos-device.c file in your sylixos branch. 

Sorry, I forgot that you are not using the primary repository...

Now, the mirror at Github should be updated, too.

**Comment by gongyujian** [comment]
OK, I'll merge and test again.

**Comment by gongyujian** [comment]
- My new submission has been tested on the x86 and PowerPC P4080 and MIPS platform.

- Not all systems support printf's %$1s, so it is not recommended to use these formatted outputs.
  E.g MLWI=%1$s DwFcIn%5$c.

**Comment by gollux** [comment]
> - My new submission has been tested on the x86 and PowerPC P4080 and MIPS platform.

Fine. Unless you find any further problems, I will keep my simple
probing mechanism.

> - Not all systems support printf's %$1s, so it is not recommended to use these formatted outputs.
>   E.g MLWI=%1$s DwFcIn%5$c.

Good point, I will fix it.

**Comment by gongyujian** [comment]
OK, Thanks.

**Comment by gongyujian** [comment]
- I have added the support for a SylixOS environment.

- All the work so far has been completed.

**Comment by gollux** [comment]
> - All the work so far has been completed.

Thanks, I merged it to master.

**Comment by gollux** [comment]
> Not all systems support printf's %$1s, so it is not recommended to use these formatted outputs.
> E.g MLWI=%1$s DwFcIn%5$c.

Should be fixed in current master.

**Comment by gongyujian** [comment]
OK, Thanks.

**Pull request closed without merging**
